### PR TITLE
Improve usage guide

### PR DESCRIPTION
**Pull request by luisgerhorst**

### CODE REVIEW

**Comment by luisgerhorst** [comment]
I was wondering if there is any reason to enable `eclim-mode` in a buffer when `eclimd` is not running. If not why not automatically start `eclimd` when `eclim-mode` is enabled? (Or maybe the first time a command that requires `eclimd` is invoked, I'd prefer the former). Similar modes like [`meghanada-emacs`](https://github.com/mopemope/meghanada-emacs) or JDEE also do that (althought I understand that `eclimd` is a little more obstrusive than the Meghanade server since at least on macOS it adds an icon to the Dock).

__Edit:__ Same thing with the projects, is it a good idea to ask the user to create a project when a command is called?
__Edit 2:__ Maybe also inform the user that additional software has to be installed when `emacs-eclim` is invoked the first time and does not find the required executeables? This would allow users to install the package from MELPA and be guided through the setup.

**Comment by tdavis** [comment]
My person reasoning for not auto-starting eclimd is that I usually start it from within Eclipse so that I can do occasional debugging there. If eclimd started implicitly, I would need to remember that and make sure I always start it in eclipse first (and hope the auto-start code takes into account that eclimd *can* be started externally)

**Comment by luisgerhorst** [comment]
I see what you mean, an option would sure be usefull (to control that eclimd gets autostarted). Would you agree when I say that most users would prefer it when the server gets started automatically? Some more feedback on this would be great if someone reads this and uses eclim :)

**Comment by luisgerhorst** [comment]
Also the code would for shure have to detect if eclimd is already running.

**Pull request merged**
