### PR TITLE
fix eclimd-start sentinel to not error when not in project

### PR DESCRIPTION
**Pull request by nverno**
Stops eclimd-start process setinel from erroring when started
from directory that is not already an eclim project.

### CODE REVIEW

**Comment by nverno** [comment]
solve "error in process-filter" #96

**Comment by nloyola** [comment]
Hi @nverno. I'm trying out this commit, but when I do `M-x eclimd-start` after opening a Java file in my project I get: `Not currently in eclim project`.

I'll look into it further to see if  it's my setup.

**Comment by nverno** [comment]
Yea, I see the same issue. There also is an issue with `eclimd-stop`, which hangs on `accept-process-output`.

**Comment by nverno** [comment]
Hm, it breaks the buttercup tests though since the mockup isnt a real process. What to do...
It would be nice to have a better mock-up to write tests against.

**Comment by nloyola** [comment]
Hi @nverno. I tried your latest commit and the start sentinel portion works for me now. However, stopping eclimd still hangs and the tests fail. Do you want me to look into that?

**Comment by nverno** [comment]
I think the stopping eclimd should add a check in `eclimd--match-process-output`, eg. line 255

```
(while (and (process-live-p eclimd-process) (not finished-p)
   ....)
```
but it breaks the previous buttercup tests that rely on the fake mock-up process. The `called-interactive-p` is hacky and the specs work when I run them locally (emacs 27.0.5), but I don't know if that is due to a change in the function or something else.

I've only just started looking into buttercup, so I'm not sure how to remedy the testing sitch.

**Comment by nverno** [comment]
I'll break it into two issues, this just deals with the eclim starting outstide project part

**Pull request merged**
