### PR TITLE
Autostart eclimd

### PR DESCRIPTION
**Pull request by luisgerhorst**
> Autostart eclimd from within Emacs whenever eclim-mode is enabled or global-eclim-mode requires eclimd to determine if eclim-mode should be enabled in a buffer. When eclimd was started outside of Emacs it is detected and eclimd does not get started a second time. Autostarting can be disabled by setting eclimd-autostart to nil (default t), eclimd-autostart-with-default-workspace controls whether eclimd asks for a workspace when it gets autostarted (default to nil).

I'll also try to implement a asynchronous version of this, especially the starting of eclimd when global eclim mode required it is very annoying. Now `stop-eclimd` is also added to `kill-emacs-hook` when it is started, is that a bad idea for some reason?

### CODE REVIEW

**Comment by luisgerhorst** [comment]
Oops, give me some time to fix that failing define-error

**Comment by luisgerhorst** [comment]
So as I just found out `define-error` was added in Emacs 24.4, should I modify the code not to use this feature or change the ci test to install 24.4? Currently it uses 24.3.

__Edit:__ I found [this page](https://launchpad.net/~cassou/+archive/ubuntu/emacs) that says `ppa:cassou/emacs` is no longer maintained, he suggests using `ppa:ubuntu-elisp/ppa` instead.

__Edit 2:__ Ok I think I'd suggest using `ppa:adrozdoff/emacs` since it has both Emacs 24.4 and Emacs 25.

**Comment by nloyola** [comment]
There's a lot of stuff in this pull request. I will cherry-pick the changes you've made for Travis CI right away. But it will take me more time to go through the auto start content.

It may be better to split this into two different pull requests.

**Comment by luisgerhorst** [comment]
Yeah sorry for that mess 😅 I'll create a second one for the Travis CI stuff tomorrow. Is it safe to just force push changes to this branch that remove those commits or is there a nicer way?

**Comment by nloyola** [comment]
Once I merge your separate Travis CI pull request, you'll be able to rebase this branch to master and you'll then be left with the Elisp changes only.

**Comment by luisgerhorst** [comment]
Ok 👍🏼

**Comment by nloyola** [comment]
Is the reason for making Emacs 24.4 a requirement in this pull request? In your other pull request, the `.travis.yml`file had Emacs 24.3.

I'm trying out your changes and will merge them soon.

**Comment by luisgerhorst** [comment]
Yeah the define-error in this one requires 24.4, with the other one you could maybe go down with the requirements even futher.

**Comment by nloyola** [comment]
Thanks for the great work you are doing with the pull request. It will be great to add this functionality to the project.

With this pull request, when opening a Java file on my computer, it takes about 10 seconds to start the Eclim server. During this time the UI is blocked. This behaviour may confuse existing users. Would it be better to have a configuration option in `emacs-eclim` for autostart? This way users can opt-in.

Also, when autostarting, could the code switch to the `*eclimd*` buffer? This way the user can be made aware of what is going on. 

And, I believe I found a bug. If I press <kbd>Ctrl-g</kbd> while the Eclim server is being started, and then press <kbd>Ctrl-x Ctrl-c</kbd>, I get the message:

```
Eclim was unable to connect to eclimd. You can start eclimd using M-x start-eclimd
```

Followed by:

```
error in process filter: Symbol’s value as variable is void: output
```

This also happens when I press <kbd>Ctrl-x Ctrl-c</kbd> repeatedly.

Then, after waiting a few more seconds and pressing <kbd>Ctrl-x Ctrl-c</kbd> I can then exit Emacs.

**Comment by luisgerhorst** [comment]
Thanks for the review, switching to the eclimd buffer is a great idea. I'll look into the bug you found. I see that the new behaviour will confuse existing users but I think for new users it should be turned on by default. What about adding it to the default suggested configuration and maybe turning it on by default in a later release?

**Comment by nloyola** [comment]
@luisgerhorst in response to the following:

> What about adding it to the default suggested configuration and maybe turning it on by default in a later release?

Thats perfect. :smiley:

**Comment by ilanpillemer** [comment]
10 seconds is a very long time to lock anything.

**Comment by luisgerhorst** [comment]
@ilanpillemer I think I'll skip making it show the eclimd buffer and step straight to creating a version that does not block.

**Comment by luisgerhorst** [comment]
@nloyola `d36db8f` also fixes the bug you described :)

**Comment by luisgerhorst** [comment]
That should be it for now. I'll squash the commits after your review :)

**Comment by nloyola** [comment]
I'm trying out the changes, but the Eclim server is not starting form me. I get the following in the `*Messages*` buffer:

```
error in process filter: cond: Eclim was unable to connect to eclimd. You can start eclimd using M-x start-eclimd
```

I get the same message both after I open a Java file and when I use the command `start-eclimd`.

I'll look into it some more and let you.

**Comment by luisgerhorst** [comment]
Hmm for now was unable to reproduce this, [here's a minimal config I tried](https://gist.github.com/luisgerhorst/ad64e22784433901e5cca4ec53f7d0b9) (note: seems as if yasnippet is no longer an optional dependency).

**Comment by nloyola** [comment]
I can get it to start now, but my `*eclimd*` buffer is empty. Was this your intention?

I got in the habit of always watching the `*eclimd*` buffer and waiting for the `Eclim Server Started` message, before using any of the eclim commands.

I guess my original problem was due to me using eclim commands (i.e. `eclim-problems`) before the server had started. Is it possible to change the error message to say something like?

```
Please wait, Eclim server has not started yet
```

Thanks for your hard work, this PR is a great improvement for this package.

**Comment by nloyola** [comment]
If I add this code, then the `*eclimd*` buffer shows the Eclim Server's output:

```emacs-lisp
(defun eclimd--ordinary-insertion-filter (proc string)
  (when (buffer-live-p (process-buffer proc))
    (with-current-buffer (process-buffer proc)
      (let ((moving (= (point) (process-mark proc))))
        (save-excursion
          ;; Insert the text, advancing the process marker.
          (goto-char (process-mark proc))
          (insert string)
          (set-marker (process-mark proc) (point)))
        (if moving (goto-char (process-mark proc)))))))

(setq eclimd--comint-process-filter 'eclimd--ordinary-insertion-filter)
```

**Comment by nloyola** [comment]
If you are OK with me adding the code to display the server's output, I will go ahead and merge your pull request.

**Comment by luisgerhorst** [comment]
Yeah sure add the code, it will take a few days until I get to this again, the message you proposed to instruct the user to wait before using the commands is possible, I'll create a commit soon. The eclim buffer should not be empty.

**Comment by luisgerhorst** [comment]
I wonder why it does not show the ouput. Have you copied the function from comint?

**Comment by luisgerhorst** [comment]
You can also try setting the filter function from comint.el (?) directly.

**Comment by nloyola** [comment]
In your code, `eclimd--comint-process-filter` is declared a variable and assigned to `nil` and never assigned a value anywhere else. The function `eclimd--process-filter` does a `funcall` to `eclimd--comint-process-filter`. Should the variable and the `funcall` be removed? 

Perhaps, your intent was to display the output in `eclimd--process-filter` since it has this comment:

```emacs-lisp
;; Appends output to eclimd buffer.
```

**Comment by luisgerhorst** [comment]
Ok wait I think I've messed something up when committing this. I'll push a new commit in a few days

**Comment by luisgerhorst** [comment]
This should fix the missing ouput in the eclimd buffer.

**Comment by nloyola** [comment]
Squashed and merged into master in commit  1cd950ef.

**Pull request closed without merging**
