### PR TITLE
Fix constructor generation

### LINKED ISSUE #38: Does not generate constructor properly
In vim eclim allows you to generate constructors for fields by selecting them, and then running JavaConstructor. Sadly this does not work with emacs-eclim, and it only generates an empty constructor, which isn't of much use. It would be great if you guys would implement this feature, as it is the main thing preventing me from making the switch from intelliJ!

### PR DESCRIPTION
**Pull request by kwvanderlinde**
This fixes #38 by extracting all field names from the active region.

### CODE REVIEW

**Comment by nloyola** [comment]
Thanks for looking into this issue. I tested it and it works great. However, if in the master branch I call `eclim-java-constructor` without highlighting anything, a constructor without any parameters is added. If I try the same with this pull request, nothing happens.

I think this pull request should still behave in the same way.

**Comment by kwvanderlinde** [comment]
@nloyola That's weird - it seemed to work for me. I'll clear this up.

**Comment by nloyola** [comment]
I tried it again, and it works when nothing is highlighted. I'm not sure what I did wrong. I'll go ahead and merge this.

Thanks

**Comment by nloyola** [comment]
I tried this, and nothing is generated:

```
class Test {

   int x, y;

}
```

I'll submit it as a new issue and can be fixed in a new pull request.

**Comment by nloyola** [comment]
Merged into master in the following commits:

* b9815ca32d88b5390d019796a813db0d7c2fb6fe
* f5616b672557267fa91f0269e4c574dfcf4712aa
* e42c89d10fc7b49415225e30271019d024fba1d3
* 57f05552d197010b320b8ac6c8e4bc7258ca222b

**Pull request closed without merging**
