### PR TITLE
More eclimd tests using mocks

### PR DESCRIPTION
**Pull request by luisgerhorst**

### CODE REVIEW

**Comment by luisgerhorst** [comment]
I'm not really sure but shouldn't the coverage have increased? Or is this only about ERT tests? (If so, why? Can coveralls not also run Buttercup tests?)

**Comment by nloyola** [comment]
Merged into master in commits: b394882312118e268856bde80e527911242409e0, 24a69a120c0c6e9c6dc4d51ea3318a2d0485843c, and d84bb90137c06734ea6677bd6ff218422c92ea96.

**Comment by nloyola** [comment]
I think you are right. Coverage is only showing ERT tests. I'll investigate.

**Comment by luisgerhorst** [comment]
Ok, I can also look into it tomorrow if you're busy

**Comment by nloyola** [comment]
I've tried quite a few things, but still cannot make it work on the master branch. Please give it a try.

**Pull request merged**
